// <auto-generated />
using BlazorApp1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp1.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20191005104947_Student")]
    partial class Student
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorApp1.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "74a1617c-3601-470a-80a7-07bbaac36678",
                            FirstName = "Sayed",
                            LastName = "Hossain",
                            School = "Hazi Mohosin college"
                        },
                        new
                        {
                            StudentId = "9cd97e0a-db5d-48ce-914b-ed0f64fc60f4",
                            FirstName = "Mizanur",
                            LastName = "Rahman",
                            School = "Muslim High School"
                        },
                        new
                        {
                            StudentId = "b0cfaaa6-22bd-445b-9f68-f8b32c7fa31d",
                            FirstName = "Hasanur",
                            LastName = "Rasid",
                            School = "Nasirabad Boys School"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
